version: "3.9"

services:
 client:
  image: postgres:latest
  restart: always
  environment:
   PGDATABASE: ${PGDATABASE}
   PGUSER: ${PGUSER}
   PGPASSWORD: ${PGPASSWORD}
   PGHOST: ${PGHOST}
   PGPORT: ${PGPORT}
   PGSSLMODE: ${PGSSLMODE}
  command: ["sleep", "infinity"]
 adminer:
  image: adminer
  restart: always
  ports:
   - 8080:8080
